[package]
name = "tera"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Jinja2/Django templates in pure Rust"
homepage = "https://github.com/Keats/tera"
repository = "https://github.com/Keats/tera"
keywords = ["template", "html", "jinja", "django", "markup"]

[dependencies]
glob = "0.2"
serde = "0.7"
serde_json = "0.7"
clippy = {version = "~0.0.35", optional = true}

[features]
default = []
dev = ["clippy"]

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
