[package]
name = "tera"
version = "0.1.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]

[dependencies]
glob = "0.2"
serde = "0.7"
serde_json = "0.7"
clippy = {version = "~0.0.35", optional = true}

[features]
default = []
dev = ["clippy"]


[profile.bench]
lto = true
codegen-units = 1
opt-level = 3
